/*	Group Student Name: Khanh Le, Mohammed Arab
    Student Email: kle6951@mtroyal.ca, marab@mtroyal.ca
    File Name: Model.c
    Instructor: Paul Pospisil
    Assignment: Flappy Bird - Stage 3
    Previous Update: March 17th, 2023
    Recent Update: April 5th, 2023
*/
#include "model.h"

#define GAP 90
/* Function name: initialize_bird
   Input: Bird *bird
          unsigned int y_pos
          unsigned int gravity
    Output: None
    Function details: The function initialize all the
    properties of the bird. Only the y position and
    the gravity are determined by the caller
*/
void initialize_bird(Bird *bird, unsigned int y_pos, unsigned int gravity)
{
    bird->y_pos = y_pos;
    bird->alive = 1;
    bird->velocity = 1;
    bird->gravity = gravity;
}

/*  Function name: init_pipes
    Input: Pipe *pipe
    Output: None
    Function details:
Initializes an array of pipes with random start gaps and given x positions.

An array of Pipe structs to be initialized

The number of pipes in the array

The pipes array will be initialized with x positions starting at 180 and incrementing by 180
with each subsequent Pipe struct, and random start gaps generated by the random_int function.
*/
void init_pipes(Pipe *pipe)
{
    pipe->x = 639; /*639;*/
    pipe->start_gap = random_int();
}

/*  Function name: random_int
    Input: None
    Output: a random integer between 30 and 223.
    Function details: Generates a random integer between 30
and 223 (inclusive).
*/
int random_int()
{
    static int initialized = 0; /*static variable to keep track of initialization*/
    if (!initialized)
    {
        srand(time(NULL)); /*seed the random number generator*/
        initialized = 1;
    }
    return rand() % (223 - 30 + 1) + 30; /*return a random integer in the specified range*/
}

/*
    Function Name: update_pipes
    Input: Pipe *pipe
           int pipe_speed
pipes[]: An array of Pipe structures representing the pipes in the game.
num_pipes: An integer representing the number of pipes in the array.
pipe_speed: An integer representing the speed of the pipes in the game.
    Output: None
    Function Details:
This function updates the position of the pipes in the pipes array.
It takes in the pipes array, the number of pipes in the array and
the speed of the pipes as input arguments.
*/
void update_pipes(Pipe *pipe, int pipe_speed)
{
    /*Check if the first pipe in the array has moved off the screen*/
    if (pipe->x <= 250)
    {
        /*clear_pipes(base, 250, pipe->start_gap);*/
        pipe->x = 639;
        pipe->start_gap = random_int();
    }
    else
    {
        /*Update the position of the pipe*/
        pipe->x -= pipe_speed;
    }
}

/*  Function name: update_bird
    Input: Bird *bird
           UINT32 input
    Output: None
    Function details: The function updates the y position of
    the bird upward if the player hits space bar, otherwise
    the y position of the bird is updated downward

*/
void update_bird(Bird *bird, char input)
{
    if (Cconis())
    {
        input = (char)Cnecin();
    }

    if (input == SPACE_KEY)
    {
        bird->velocity = -13; /*13*/
        bird->old_y_pos = bird->y_pos;
        bird->y_pos += bird->velocity;
         flaps_sound();
    }
    Vsync();
}

/*  Function name: bird_falls
    Inputs: Bird *bird
    Output: None
    Function details: The function performs
    calculating the new vertex of the bird
    when it falls by applying the value of 
    the bird velocity to its current vertex
*/
void bird_falls(Bird *bird)
{
    bird->velocity += bird -> gravity;
    bird->old_y_pos = bird->y_pos;
    bird->y_pos += bird->velocity;
   Vsync();
}


/*  Function name: update_score
    Input: Score *player_score
           unsigned int alive
           int strike
    Output: None
    Function details: While the bird is alive, the
    function updates the score if the bird sucessfully
    passes a pair of pipe.  When there is a strike,
    the earned point is double and added to the total
    score
*/
void update_score(Score *player_score, int strike)
{
    if (strike == 1)
    {
        player_score->earned_score = player_score->earned_score * 2;
        player_score->score = player_score->score + player_score->earned_score;
    }
    else
    {
        player_score->score += player_score->earned_score;
    }
}

/*  Function name: extract_score
    Input: Score *player_score
    Output: None
    Function details: The function extracts each digit from the
    score and store it in the thousandth_digit, hundredth_digit,
    tenth_digit, oneth_digit data member of the score instance.
*/
void extract_score(Score *player_score)
{
    unsigned int thousandth, hundreth, tenth, oneth;
    player_score->thousandth_digit = (player_score->score / 1000) % 10;
    player_score->hundredth_digit = (player_score->score / 100) % 10;
    player_score->tenth_digit = (player_score->score / 10) % 10;
    player_score->oneth_digit = player_score->score % 10;
}

/*  Function name: check_collision
    Input: Bird *bird
           Pipe *pipe
    Output: int
    Function details: The function perform boundary checking
    to check all the possible collision between the bird and
    the pipes, and between the bird and the ground. If the
    collision is detect, 1(ie: true) is returned, otherwise
    0(ie: false) is returned.
*/
int check_collision(Bird *bird, Pipe *pipe)
{

    /*Check if the bird's x-coordinate is within the x-coordinate range of the pipe*/
    if (((bird->x_pos * LONG_WORD) + BIRD_WIDTH >= pipe->x) && (bird->x_pos * LONG_WORD) <= pipe->x + PIPE_WIDTH)
    {
        /* Check if the bird's y-coordinate is within the y-coordinate range of the gap in the pipe*/
        if ((bird->y_pos < pipe->start_gap) || (bird->y_pos + BIRD_WIDTH > pipe->start_gap + GAP))
        {
            /*The bird has collided with a pipe*/
            collision_sound();
            return 1;
        }
    }
    /* Check if the bird's y-coordinate is within the y-coordinate range of the screen height*/
    if (bird->y_pos - BIRD_WIDTH <= MIN_BIRD_LOCATION || bird->y_pos >= MAX_BIRD_LOCATION)
    {
        /*The bird has collided with a pipe*/
        collision_sound();
        return 1;
    }

    /*The bird has not collided with any pipes*/
    return 0;
}

/*  Function name: score_detection
    Input: Bird *bird
           Pipe *pipe
    Output: int score_dection: 1 if detecting the player can earn a score,
                               otherwise, 0 is returned
    Function details: The function detects when the bird gets to be in the
    gap between the top and bottom bird, then the player can earn point(s).
*/
int score_detection(Bird *bird, Pipe *pipe)
{

    if (bird->x_pos * LONG_WORD >= (pipe->x + PIPE_WIDTH) && pipe->x >= 315)
    {
        return 1;
    }

    /*The player has not scored any point*/
    return 0;
}

/*  Function name: strike_detection
    Input: Score *score
    Output: int strike detection: 1 if detecting the player has a strike,
                                  otherwise 0 is returned
    Function details: The function detects when the player earns point(s)
    10 times.
*/
int strike_detection(Score *score)
{
    if (score->score_counter == STRIKE + 1)
    {
        score->score_counter = 0;
        return 1;
    }
    return 0;
}
