tst_rend: tst_rend.o raster.o model.o render.o font.o clear_qk.o
	cc68x -g tst_rend.o raster.o model.o render.o font.o clear_qk.o -o tst

tst_rend.o: tst_rend.c raster.h render.h model.h font.h
	cc68x -g -c tst_rend.c

raster.o: raster.c raster.h render.h model.h font.h
	cc68x -g -c raster.c

model.o: model.c raster.h render.h model.h font.h
	cc68x -g -c model.c

render.o: render.c raster.h render.h model.h font.h
	cc68x -g -c render.c

font.o: font.c raster.h render.h model.h font.h
	cc68x -g -c font.c

clear_qk.o: clear_qk.s
	gen -D -L2 clear_qk.s
